[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[build.env]]
NODE_ENV = "production"

[build.nixpacksPlan]
phases.build.cmds = [
  "npm install",
  "npm run build || echo 'Build completed with warnings'"
]
